### ISSUE TITLE
Campgrounds/campsites both have `type=Campground` in CartoDB points_of_interest table

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/cron-tasks#10]
I need to be able to query out just the campgrounds. Here's a map that exhibits this issue: http://www.nps.gov/maps/full.html?mapId=4850b2b6-6517-4ac7-b273-97426eb4301d. And here is the query I'm using to pull the data from CartoDB:

`SELECT name, places_id, type, the_geom FROM points_of_interest WHERE unit_code='yell' AND type='Campground'`

**Comment by jimmyrocks** [comment]
tags are updated now, the update script wasn't looking for changed tags
